model_config_dict:
  # Small model for CPU sanity run
  vocab_size: 50257
  n_positions: 512
  max_position_embeddings: 512
  n_embd: 384
  n_layer: 4
  n_head: 6
  n_kv_head: 2
  rotary_dim: 64         # must match n_embd / n_head
  intermediate_size: 1536
  activation: swiglu
  norm_type: rmsnorm
  norm_eps: 1e-5
  dropout: 0.0
  attention_dropout: 0.0
  residual_dropout: 0.05
  embed_dropout: 0.05
  tie_word_embeddings: true
  use_cache: true
  attention_bias: false
  mlp_bias: false
  flash_attention: false
  sliding_window: null
  rope_theta: 10000.0
  gradient_checkpointing: false

data:
  use_hf: true
  dataset_path: "wikitext"   # Reliable dataset with native train/val splits
  dataset_config_name: "wikitext-2-raw-v1"
  hf_text_column: "text"
  streaming: true                       # stream large dataset
  # Use native train/validation splits
  dataset_split_train: "train"
  dataset_split_val: "validation"
  max_length: 192
  validation_split: 0.0   # ignored when dataset_split_val is set
  quality_filtering: false
  deduplication: false
  shuffle_buffer_size: 1000

optim:
  optimizer: "adamw"
  learning_rate: 8.0e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  eps: 1e-8
  clip_grad_norm: 1.0
  warmup_steps: 600
  lr_scheduler: "cosine"
  total_steps: 6000

training:
  batch_size: 8
  micro_batch_size: 2
  gradient_accumulation_steps: 4
  mixed_precision: "fp32"
  compile_model: false
  checkpoint_interval: 500
  eval_interval: 100
  log_interval: 20
  max_eval_batches: 10
  seed: 42
  save_total_limit: 2

experiment:
  experiment_name: "wikitext_stream_quick"
  output_dir: "outputs/wikitext_stream_quick"
  use_wandb: false
  sample_every: 200
  sample_length: 80
  sample_temperature: 0.7
  sample_top_k: 50
  sample_top_p: 0.9









  # data:
  # use_hf: true
  # dataset_path: "EleutherAI/the_pile"
  # dataset_config_names:  # Multiple subsets (I need to implement this)
  #   - "ArXiv"
  #   - "OpenWebText2" 
  #   - "StackExchange"
  #   - "Wikipedia (en)"
  #   - "PubMed Abstracts"
  #   - "Github"
  #   - "Books3"
  #   - "Ubuntu IRC"
  # hf_text_column: "text"
  # streaming: true
  # interleave_probabilities: [0.15, 0.20, 0.10, 0.15, 0.10, 0.10, 0.15, 0.05]