name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -r deep/requirements.txt
          pip install black flake8 mypy pytest
      - name: Lint
        run: |
          black --check deep/src deep/train_ultrathink.py || true
          flake8 deep/src deep/train_ultrathink.py || true
          mypy deep/src || true
      - name: PyTest (CPU)
        run: |
          pytest -q

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd deep
          docker build -t ultrathink:ci .
